<?php

declare(strict_types=1);

namespace Omnichannel\Addons\Agent\Services\AgentWorkspace\Templates;

final class BuiltinChatTemplateCatalog
{
    /**
     * @return list<array<string, mixed>>
     */
    public static function definitions(): array
    {
        return [
            [
                'key' => 'create_project_month',
                'title' => 'Tạo project mới',
                'description' => 'Tạo Content Project tháng hiện tại cho site đang chọn.',
                'skill_key' => 'content_project.create',
                'prompt_template' => 'Tạo Content Project tháng {{month}} cho {{site_name}}',
                'variables' => [
                    ['key' => 'month', 'label' => 'Tháng', 'type' => 'month', 'required' => true],
                    ['key' => 'site_name', 'label' => 'Website', 'type' => 'text', 'required' => true],
                ],
                'category' => 'content_project',
                'sort_order' => 1,
                'is_featured' => true,
            ],
            [
                'key' => 'create_project_from_map',
                'title' => 'Tạo project từ Topical Map',
                'description' => 'Tạo Content Project từ Topical Map đã duyệt.',
                'skill_key' => 'keyword.preview_project',
                'prompt_template' => 'Tạo Content Project từ Topical Map đã duyệt',
                'variables' => [],
                'category' => 'keyword_intelligence',
                'sort_order' => 2,
                'is_featured' => true,
            ],
            [
                'key' => 'analyze_keywords_pending',
                'title' => 'Phân tích từ khóa',
                'description' => 'Phân tích những từ khóa chưa xử lý trong workspace này.',
                'skill_key' => 'keyword.analyze',
                'prompt_template' => 'Phân tích những từ khóa chưa xử lý trong workspace này',
                'variables' => [],
                'category' => 'keyword_intelligence',
                'sort_order' => 3,
                'is_featured' => true,
            ],
            [
                'key' => 'check_project_status',
                'title' => 'Kiểm tra project',
                'description' => 'Cho tôi biết project này đang kẹt ở đâu.',
                'skill_key' => 'content_project.status',
                'prompt_template' => 'Cho tôi biết project này đang kẹt ở đâu',
                'variables' => [],
                'category' => 'content_project',
                'sort_order' => 4,
                'is_featured' => true,
            ],
            [
                'key' => 'rerun_images',
                'title' => 'Chạy lại ảnh',
                'description' => 'Chạy lại bước tạo ảnh cho những bài đã chọn.',
                'skill_key' => 'content_project.rerun',
                'prompt_template' => 'Chạy lại bước tạo ảnh cho những bài tôi chọn',
                'variables' => [],
                'category' => 'content_project',
                'sort_order' => 5,
                'is_featured' => true,
            ],
            [
                'key' => 'schedule_approved',
                'title' => 'Lên lịch đăng',
                'description' => 'Lên lịch đăng các bài đã duyệt.',
                'skill_key' => 'content_project.schedule',
                'prompt_template' => 'Lên lịch đăng các bài đã duyệt',
                'variables' => [],
                'category' => 'content_project',
                'sort_order' => 6,
                'is_featured' => true,
            ],
            [
                'key' => 'daily_report',
                'title' => 'Báo cáo hôm nay',
                'description' => 'Tóm tắt những gì đã chạy, lỗi và bài cần chú ý hôm nay.',
                'skill_key' => 'operations.daily_report',
                'prompt_template' => 'Tóm tắt những gì đã chạy, lỗi và bài cần chú ý hôm nay',
                'variables' => [],
                'category' => 'operations',
                'sort_order' => 7,
                'is_featured' => true,
            ],
            [
                'key' => 'add_keywords_project',
                'title' => 'Thêm keyword vào project',
                'description' => 'Thêm danh sách keyword/bài vào Content Project đang mở.',
                'skill_key' => 'content_project.add_items',
                'prompt_template' => 'Thêm các keyword sau vào project hiện tại',
                'variables' => [],
                'category' => 'content_project',
                'sort_order' => 8,
                'is_featured' => true,
            ],
            [
                'key' => 'generate_pending',
                'title' => 'Generate bài chưa chạy',
                'description' => 'Chạy tạo bài cho item chưa chạy (preview trước).',
                'skill_key' => 'content_project.generate',
                'prompt_template' => 'Chạy tạo bài cho tất cả item chưa chạy',
                'variables' => [],
                'category' => 'content_project',
                'sort_order' => 9,
                'is_featured' => true,
            ],
            [
                'key' => 'review_selected',
                'title' => 'Bắt đầu duyệt',
                'description' => 'Mở quy trình duyệt bài trong project.',
                'skill_key' => 'content_project.start_review',
                'prompt_template' => 'Bắt đầu duyệt',
                'variables' => [],
                'category' => 'content_project',
                'sort_order' => 10,
                'is_featured' => true,
            ],
            [
                'key' => 'check_publish_failures',
                'title' => 'Kiểm tra publish lỗi',
                'description' => 'Xem hàng đợi đăng và gợi ý retry.',
                'skill_key' => 'content_project.publishing_queue',
                'prompt_template' => 'Kiểm tra publish lỗi',
                'variables' => [],
                'category' => 'publishing',
                'sort_order' => 11,
                'is_featured' => true,
            ],
            [
                'key' => 'archive_completed',
                'title' => 'Archive project hoàn tất',
                'description' => 'Archive sau khi publish xong — luôn cần confirmation.',
                'skill_key' => 'content_project.archive',
                'prompt_template' => 'Archive project sau khi publish hết',
                'variables' => [],
                'category' => 'content_project',
                'sort_order' => 12,
                'is_featured' => true,
            ],
            [
                'key' => 'keyword_opportunities',
                'title' => 'Tìm keyword cơ hội',
                'description' => 'Phân tích từ khóa chưa xử lý.',
                'skill_key' => 'keyword.analyze',
                'prompt_template' => 'Tìm keyword cơ hội',
                'variables' => [],
                'category' => 'keyword_intelligence',
                'sort_order' => 13,
                'is_featured' => true,
            ],
            [
                'key' => 'serp_content_gap',
                'title' => 'Phân tích content gap',
                'description' => 'Xem content gap từ SERP.',
                'skill_key' => 'serp.list_content_gaps',
                'prompt_template' => 'Xem content gap',
                'variables' => [],
                'category' => 'serp_intelligence',
                'sort_order' => 14,
                'is_featured' => true,
            ],
            [
                'key' => 'site_health_check',
                'title' => 'SEO health check',
                'description' => 'Kiểm tra sức khỏe site.',
                'skill_key' => 'operations.site_health',
                'prompt_template' => 'Kiểm tra site health',
                'variables' => [],
                'category' => 'operations',
                'sort_order' => 15,
                'is_featured' => true,
            ],
            [
                'key' => 'weekly_planning',
                'title' => 'Weekly planning proposal',
                'description' => 'Đề xuất kế hoạch tuần — không auto-execute.',
                'skill_key' => 'general.help',
                'prompt_template' => 'Đề xuất kế hoạch content tuần này cho site hiện tại',
                'variables' => [],
                'category' => 'planning',
                'sort_order' => 16,
                'is_featured' => true,
            ],
        ];
    }
}
