<?php

declare(strict_types=1);

namespace Omnichannel\Addons\Agent\Services\AgentWorkspace\Skills;

final class ContentProjectSkills
{
    /**
     * @return list<array<string, mixed>>
     */
    public static function definitions(): array
    {
        return [
            [
                'key' => 'content_project.list',
                'slash_command' => '/list-projects',
                'name' => 'Danh sách Content Project',
                'description' => 'Xem các dự án nội dung của site hiện tại.',
                'category' => 'content_project',
                'capability' => 'content_project.list_projects',
                'sort_order' => 20,
                'required_scopes' => ['content-project:read'],
                'confirmation_policy' => 'none',
            ],
            [
                'key' => 'content_project.create',
                'slash_command' => '/create-project',
                'aliases' => ['/new-project', '/tao-project'],
                'name' => 'Tạo Content Project',
                'description' => 'Tạo dự án nội dung mới và thêm các bài cần thực hiện.',
                'category' => 'content_project',
                'capability' => 'content_project.create',
                'icon' => 'heroicon-o-folder-plus',
                'sort_order' => 21,
                'is_featured' => true,
                'required_scopes' => ['content-project:write'],
                'confirmation_policy' => 'preview',
                'example_prompts' => [
                    'Tạo project nội dung tháng 8',
                    'Tạo Content Project tháng này',
                ],
                'form_schema' => [
                    ['key' => 'project_name', 'label' => 'Tên project', 'type' => 'text', 'required' => true],
                    ['key' => 'month', 'label' => 'Tháng thực hiện', 'type' => 'month', 'required' => true],
                    ['key' => 'assignee_ref', 'label' => 'Người phụ trách', 'type' => 'user', 'required' => false],
                    ['key' => 'description', 'label' => 'Mô tả', 'type' => 'textarea', 'required' => false],
                    [
                        'key' => 'seed_mode',
                        'label' => 'Khởi tạo bài',
                        'type' => 'select',
                        'required' => true,
                        'default' => 'none',
                        'options' => [
                            ['value' => 'none', 'label' => 'Không có'],
                            ['value' => 'manual', 'label' => 'Nhập ngay'],
                            ['value' => 'topical_map', 'label' => 'Lấy từ Topical Map'],
                        ],
                    ],
                    ['key' => 'items_text', 'label' => 'Danh sách bài ban đầu', 'type' => 'textarea', 'required' => false, 'help' => 'Mỗi dòng một bài / keyword'],
                ],
                'input_schema' => [
                    'project_name' => ['type' => 'string', 'required' => true],
                    'month' => ['type' => 'string', 'required' => true],
                ],
                'result_presentation' => [
                    'primary_link' => 'content_project',
                ],
            ],
            [
                'key' => 'content_project.update',
                'slash_command' => '/update-project',
                'name' => 'Cập nhật Content Project',
                'description' => 'Cập nhật metadata Content Project.',
                'category' => 'content_project',
                'capability' => 'content_project.update',
                'sort_order' => 21.5,
                'required_scopes' => ['content-project:write'],
                'confirmation_policy' => 'preview',
                'availability_policy' => ['requires_context' => ['project_ref']],
                'form_schema' => [
                    ['key' => 'project_ref', 'label' => 'Content Project', 'type' => 'project', 'required' => true],
                    ['key' => 'project_name', 'label' => 'Tên mới', 'type' => 'text', 'required' => false],
                ],
            ],
            [
                'key' => 'content_project.status',
                'slash_command' => '/project-status',
                'name' => 'Trạng thái project',
                'description' => 'Xem project đang kẹt ở đâu.',
                'category' => 'content_project',
                'capability' => 'content_project.get_status',
                'sort_order' => 22,
                'is_featured' => true,
                'required_scopes' => ['content-project:read'],
                'confirmation_policy' => 'none',
                'availability_policy' => ['requires_context' => ['project_ref']],
                'form_schema' => [
                    ['key' => 'project_ref', 'label' => 'Content Project', 'type' => 'project', 'required' => true],
                ],
                'example_prompts' => [
                    'Project này còn bao nhiêu bài chưa duyệt?',
                    'Cho tôi biết project đang kẹt ở đâu',
                    'kiểm tra project bị kẹt',
                ],
            ],
            [
                'key' => 'content_project.list_items',
                'slash_command' => '/list-project-items',
                'name' => 'Danh sách bài trong project',
                'description' => 'Xem items của Content Project.',
                'category' => 'content_project',
                'capability' => 'content_project.list_items',
                'sort_order' => 22.5,
                'required_scopes' => ['content-project:read'],
                'availability_policy' => ['requires_context' => ['project_ref']],
                'form_schema' => [
                    ['key' => 'project_ref', 'label' => 'Content Project', 'type' => 'project', 'required' => true],
                ],
            ],
            [
                'key' => 'content_project.add_items',
                'slash_command' => '/add-project-items',
                'name' => 'Thêm bài vào project',
                'description' => 'Thêm danh sách bài vào Content Project.',
                'category' => 'content_project',
                'capability' => 'content_project.add_items',
                'sort_order' => 23,
                'is_featured' => true,
                'required_scopes' => ['content-project:write'],
                'confirmation_policy' => 'preview',
                'availability_policy' => ['requires_context' => ['project_ref']],
                'form_schema' => [
                    ['key' => 'project_ref', 'label' => 'Content Project', 'type' => 'project', 'required' => true],
                    ['key' => 'items_text', 'label' => 'Danh sách bài', 'type' => 'textarea', 'required' => true],
                ],
                'example_prompts' => [
                    'Thêm keyword vào project',
                    'thêm 20 keyword vào project',
                    'Add keywords to project',
                ],
            ],
            [
                'key' => 'content_project.update_item',
                'slash_command' => '/update-project-item',
                'name' => 'Cập nhật bài trong project',
                'description' => 'Cập nhật một item trong Content Project.',
                'category' => 'content_project',
                'capability' => 'content_project.update_item',
                'sort_order' => 24,
                'required_scopes' => ['content-project:write'],
                'form_schema' => [
                    ['key' => 'item_ref', 'label' => 'Item', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'key' => 'content_project.generate',
                'slash_command' => '/generate-articles',
                'name' => 'Chạy tạo bài',
                'description' => 'Chạy pipeline tạo nội dung cho các bài đã chọn.',
                'category' => 'content_project',
                'capability' => 'content_project.generate',
                'sort_order' => 25,
                'is_featured' => true,
                'required_scopes' => ['content-project:generate'],
                'confirmation_policy' => 'preview',
                'availability_policy' => ['requires_context' => ['project_ref']],
                'form_schema' => [
                    ['key' => 'project_ref', 'label' => 'Content Project', 'type' => 'project', 'required' => true],
                    ['key' => 'item_refs', 'label' => 'Bài cần tạo', 'type' => 'item_multi', 'required' => false],
                ],
                'example_prompts' => ['Chạy tạo nội dung', 'Generate articles'],
            ],
            [
                'key' => 'content_project.rerun',
                'slash_command' => '/rerun-content',
                'name' => 'Chạy lại một bước',
                'description' => 'Chạy lại bước pipeline (ảnh, outline, bài…).',
                'category' => 'content_project',
                'capability' => 'content_project.rerun',
                'sort_order' => 26,
                'is_featured' => true,
                'required_scopes' => ['content-project:generate'],
                'confirmation_policy' => 'preview',
                'availability_policy' => ['requires_context' => ['project_ref']],
                'form_schema' => [
                    ['key' => 'project_ref', 'label' => 'Content Project', 'type' => 'project', 'required' => true],
                    [
                        'key' => 'rerun_step',
                        'label' => 'Bước chạy lại',
                        'type' => 'select',
                        'required' => true,
                        'options' => [
                            ['value' => 'image', 'label' => 'Ảnh'],
                            ['value' => 'outline', 'label' => 'Outline'],
                            ['value' => 'article', 'label' => 'Bài viết'],
                        ],
                    ],
                    ['key' => 'item_refs', 'label' => 'Bài đã chọn', 'type' => 'item_multi', 'required' => true],
                ],
                'example_prompts' => ['Chạy lại ảnh cho 5 bài tôi chọn'],
            ],
            [
                'key' => 'content_project.start_review',
                'slash_command' => '/start-review',
                'aliases' => ['/review-project'],
                'name' => 'Bắt đầu duyệt',
                'description' => 'Mở quy trình duyệt bài trong project.',
                'category' => 'content_project',
                'capability' => 'content_project.start_review',
                'sort_order' => 27,
                'required_scopes' => ['content-project:review'],
                'confirmation_policy' => 'preview',
                'availability_policy' => ['requires_context' => ['project_ref']],
            ],
            [
                'key' => 'content_project.approve',
                'slash_command' => '/approve-items',
                'name' => 'Duyệt bài',
                'description' => 'Duyệt các bài đã chọn trong project.',
                'category' => 'content_project',
                'capability' => 'content_project.approve',
                'sort_order' => 28,
                'required_scopes' => ['content-project:review'],
                'confirmation_policy' => 'preview',
                'availability_policy' => ['requires_context' => ['project_ref']],
            ],
            [
                'key' => 'content_project.schedule',
                'slash_command' => '/schedule-content',
                'name' => 'Lên lịch đăng',
                'description' => 'Lên lịch đăng các bài đã duyệt.',
                'category' => 'content_project',
                'capability' => 'content_project.schedule',
                'sort_order' => 29,
                'is_featured' => true,
                'required_scopes' => ['content-project:schedule'],
                'confirmation_policy' => 'preview',
                'availability_policy' => ['requires_context' => ['project_ref']],
                'form_schema' => [
                    ['key' => 'project_ref', 'label' => 'Content Project', 'type' => 'project', 'required' => true],
                    ['key' => 'item_refs', 'label' => 'Bài cần lên lịch', 'type' => 'item_multi', 'required' => false],
                    ['key' => 'scheduled_at', 'label' => 'Thời gian bắt đầu', 'type' => 'datetime', 'required' => false],
                ],
                'example_prompts' => ['Lên lịch đăng các bài đã duyệt'],
            ],
            [
                'key' => 'content_project.auto_schedule',
                'slash_command' => '/auto-schedule',
                'name' => 'Tự động lên lịch',
                'description' => 'Tự động phân bố lịch đăng theo policy site.',
                'category' => 'content_project',
                'capability' => 'content_project.auto_schedule',
                'sort_order' => 30,
                'required_scopes' => ['content-project:schedule'],
                'confirmation_policy' => 'preview',
            ],
            [
                'key' => 'content_project.unschedule',
                'slash_command' => '/unschedule-content',
                'name' => 'Hủy lịch đăng',
                'description' => 'Gỡ lịch đăng của các bài đã chọn.',
                'category' => 'content_project',
                'capability' => 'content_project.unschedule',
                'sort_order' => 31,
                'required_scopes' => ['content-project:schedule'],
                'confirmation_policy' => 'confirm',
            ],
            [
                'key' => 'content_project.move_schedule',
                'slash_command' => '/move-schedule',
                'name' => 'Dời lịch đăng',
                'description' => 'Dời lịch đăng các bài đã chọn.',
                'category' => 'content_project',
                'capability' => 'content_project.move_schedule',
                'sort_order' => 31.5,
                'required_scopes' => ['content-project:schedule'],
                'confirmation_policy' => 'confirm',
                'form_schema' => [
                    ['key' => 'project_ref', 'label' => 'Content Project', 'type' => 'project', 'required' => true],
                    ['key' => 'item_refs', 'label' => 'Bài', 'type' => 'item_multi', 'required' => true],
                    ['key' => 'scheduled_at', 'label' => 'Thời gian mới', 'type' => 'datetime', 'required' => true],
                ],
                'example_prompts' => ['dời lịch sang thứ hai', 'move schedule to Monday'],
            ],
            [
                'key' => 'content_project.publish_now',
                'slash_command' => '/publish-now',
                'name' => 'Đưa vào hàng đợi đăng',
                'description' => 'Đưa bài vào publishing queue (không gọi WP adapter trực tiếp).',
                'category' => 'content_project',
                'capability' => 'content_project.publish_now',
                'sort_order' => 32,
                'is_featured' => true,
                'required_scopes' => ['content-project:publish'],
                'confirmation_policy' => 'confirm',
                'availability_policy' => ['requires_context' => ['project_ref']],
                'example_prompts' => ['xuất bản ngay', 'publish now'],
            ],
            [
                'key' => 'content_project.retry_publish',
                'slash_command' => '/retry-publish',
                'name' => 'Thử đăng lại',
                'description' => 'Retry các bài publish lỗi trong queue.',
                'category' => 'content_project',
                'capability' => 'content_project.retry_publish',
                'sort_order' => 33,
                'required_scopes' => ['content-project:publish'],
                'confirmation_policy' => 'confirm',
                'example_prompts' => ['thử lại bài publish lỗi', 'retry failed publish'],
            ],
            [
                'key' => 'content_project.skip_publish',
                'slash_command' => '/skip-publish',
                'name' => 'Bỏ qua đăng bài',
                'description' => 'Skip item khỏi publishing queue.',
                'category' => 'content_project',
                'capability' => 'content_project.skip_publish',
                'sort_order' => 33.2,
                'required_scopes' => ['content-project:publish'],
                'confirmation_policy' => 'confirm',
            ],
            [
                'key' => 'content_project.cancel_publish',
                'slash_command' => '/cancel-publish',
                'name' => 'Hủy đăng bài',
                'description' => 'Cancel publishing item trong queue.',
                'category' => 'content_project',
                'capability' => 'content_project.cancel_publish',
                'sort_order' => 33.4,
                'required_scopes' => ['content-project:publish'],
                'confirmation_policy' => 'confirm',
            ],
            [
                'key' => 'content_project.archive',
                'slash_command' => '/archive-project',
                'name' => 'Lưu trữ project',
                'description' => 'Archive Content Project (xóa workspace local, không xóa WP).',
                'category' => 'content_project',
                'capability' => 'content_project.archive',
                'sort_order' => 34,
                'required_scopes' => ['content-project:archive'],
                'confirmation_policy' => 'confirm',
                'availability_policy' => ['requires_context' => ['project_ref']],
                'example_prompts' => ['archive project tháng 6', 'lưu trữ project'],
            ],
            [
                'key' => 'content_project.restore',
                'slash_command' => '/restore-project',
                'name' => 'Khôi phục project',
                'description' => 'Restore Content Project đã archive.',
                'category' => 'content_project',
                'capability' => 'content_project.restore',
                'sort_order' => 35,
                'required_scopes' => ['content-project:write'],
                'confirmation_policy' => 'confirm',
                'example_prompts' => ['restore project', 'khôi phục project'],
            ],
            [
                'key' => 'content_project.stop_execution',
                'slash_command' => '/stop-execution',
                'name' => 'Dừng quá trình',
                'description' => 'Dừng execution đang chạy của project.',
                'category' => 'content_project',
                'capability' => 'content_project.stop_execution',
                'sort_order' => 35.2,
                'required_scopes' => ['content-project:write'],
                'confirmation_policy' => 'confirm',
                'availability_policy' => ['requires_context' => ['project_ref']],
                'form_schema' => [
                    ['key' => 'project_ref', 'label' => 'Content Project', 'type' => 'project', 'required' => true],
                    ['key' => 'reason', 'label' => 'Lý do', 'type' => 'text', 'required' => false],
                ],
                'example_prompts' => ['dừng quá trình đang chạy', 'stop execution'],
            ],
            [
                'key' => 'content_project.resume_execution',
                'slash_command' => '/resume-execution',
                'name' => 'Tiếp tục quá trình',
                'description' => 'Resume execution đã dừng của project.',
                'category' => 'content_project',
                'capability' => 'content_project.resume_execution',
                'sort_order' => 35.4,
                'required_scopes' => ['content-project:write'],
                'confirmation_policy' => 'preview',
                'availability_policy' => ['requires_context' => ['project_ref']],
                'form_schema' => [
                    ['key' => 'project_ref', 'label' => 'Content Project', 'type' => 'project', 'required' => true],
                ],
                'example_prompts' => ['tiếp tục quá trình', 'resume execution'],
            ],
            [
                'key' => 'content_project.publishing_queue',
                'slash_command' => '/publishing-queue',
                'name' => 'Hàng đợi đăng',
                'description' => 'Xem publishing queue của site/project.',
                'category' => 'content_project',
                'capability' => 'content_project.get_publishing_queue',
                'sort_order' => 36,
                'is_featured' => true,
                'required_scopes' => ['content-project:read'],
                'example_prompts' => ['kiểm tra publish lỗi', 'check publishing failures'],
            ],
            [
                'key' => 'content_project.timeline',
                'slash_command' => '/project-timeline',
                'name' => 'Timeline project',
                'description' => 'Xem timeline / ops replay public của project.',
                'category' => 'content_project',
                'capability' => 'content_project.get_timeline',
                'sort_order' => 37,
                'required_scopes' => ['content-project:read'],
                'availability_policy' => ['requires_context' => ['project_ref']],
                'form_schema' => [
                    ['key' => 'project_ref', 'label' => 'Content Project', 'type' => 'project', 'required' => true],
                ],
            ],
        ];
    }
}
